---
title: "Overview"
output:
  blogdown::html_page:
    toc: true
menu:
  example:
    parent: Course content
    weight: 1
type: docs
editor_options: 
  chunk_output_type: console
editor: 
  markdown: 
    wrap: 72
---

::: callout-important
Due to an unexpected scheduling conflict, we have to **cancel today's lecture** (17 June). Instead, the lecture will take place tomorrow (18 June) from 15:00 to 16:30 in room O-0.007. Following the lecture, the tutorial will be held from 16:45 to 18:15 in room A-0.19.

Sorry for the inconvenience. See you tomorrow! 
:::

::: {.grid}

::: {.g-col-1}
:::


::: {.g-col-12}

### Schedule

| Session | Date | Topic |  |  | 
|---|---|---|---|---|---:
| 1 | April 15 & 16 | Introduction to Causal Inference | [{{< fa book-open >}}](https://tuhhstartupengineers-classroom.github.io/ss24-causal-data-science/slides/01_intro.html) | [{{< fa laptop >}}](week_01/week_1.html) | [{{< fa brands github >}}](https://classroom.github.com/a/qKNVakO4) |
| 2 | April 22 & 21 | Graphical Causal Models | [{{< fa book-open >}}](https://tuhhstartupengineers-classroom.github.io/ss24-causal-data-science/slides/02_graphs.html) | [{{< fa laptop >}}](week_02/week_2.html) | [{{< fa brands github >}}](https://classroom.github.com/a/eNvelq2Z) |
| 3 | April 29 & 30 | Randomized Experiments & Linear Regression | [{{< fa book-open >}}](https://tuhhstartupengineers-classroom.github.io/ss24-causal-data-science/slides/03_exper.html) | [{{< fa laptop >}}](week_03/week_3.html) | [{{< fa brands github >}}](https://classroom.github.com/a/Fnvwjrn_) |
| 4 | May 6 & 7 | Matching | [{{< fa book-open >}}](https://tuhhstartupengineers-classroom.github.io/ss24-causal-data-science/slides/04_ob_conf.html) | [{{< fa laptop >}}](week_04/week_4.html) | [{{< fa brands github >}}](https://classroom.github.com/a/ZY_8r4KL) |
| 5 | May 13 & 14 | Double Machine Learning | [{{< fa book-open >}}](https://tuhhstartupengineers-classroom.github.io/ss24-causal-data-science/slides/05_dml.html) | [{{< fa laptop >}}](week_05/week_5.html) | [{{< fa brands github >}}](https://classroom.github.com/a/m7oLFvnr) | 
| - | May 20 & 21 | Holiday | - | - | - |
| 6 | May 27 & 28 | Effect Heterogeneity | [{{< fa book-open >}}](https://tuhhstartupengineers-classroom.github.io/ss24-causal-data-science/slides/06_hte.html) | [{{< fa laptop >}}](week_06/week_6.html) | [{{< fa brands github >}}](https://classroom.github.com/a/oPhGwOmd) |
| 7 | June 3 & 4 | Unobserved Confounding & Instrumental Variables | [{{< fa book-open >}}](https://tuhhstartupengineers-classroom.github.io/ss24-causal-data-science/slides/07_unob_conf.html) | [{{< fa laptop >}}](week_07/week_7.html) | [{{< fa brands github >}}](https://classroom.github.com/a/R80VGxLm) |
| 8 | June 10 & 11 | Recap | - | [{{< fa laptop >}}](week_08/week_8.html) | [{{< fa brands github >}}](https://classroom.github.com/a/1DoD8H5P) |
| 9 | June 18 | Difference-in-Differences (1/2) | [{{< fa book-open >}}](https://tuhhstartupengineers-classroom.github.io/ss24-causal-data-science/slides/08_did.html) | [{{< fa laptop >}}](week_09/week_9.html) | [{{< fa brands github >}}](https://classroom.github.com/a/TvLAqy53) |
| 10 | June 24 & 25 | Difference-in-Differences (2/2) | [{{< fa book-open >}}](https://tuhhstartupengineers-classroom.github.io/ss24-causal-data-science/slides/08_did.html) | [{{< fa laptop >}}](week_10/week_10.html) | [{{< fa brands github >}}](https://classroom.github.com/a/AUAr8zj4) |
| 11 | July 1 & 2 | Synthetic Control (1/2)  | [{{< fa book-open >}}](https://tuhhstartupengineers-classroom.github.io/ss24-causal-data-science/slides/09_synth_c.html) | [{{< fa laptop >}}](week_11/week_11.html) | [{{< fa brands github >}}](https://classroom.github.com/a/A7dxfkG_) |
| 12 | July 8 & 9 | Synthetic Control (2/2) | [{{< fa book-open >}}](https://tuhhstartupengineers-classroom.github.io/ss24-causal-data-science/slides/09_synth_c.html) | [{{< fa laptop >}}](week_12/week_12.html) | [{{< fa brands github >}}](https://classroom.github.com/a/oQuAlVgM) |



: {tbl-colwidths="[10, 40, 90, 10, 10, 10]"}

:::

::: {.g-col-1}
:::

:::

